project:
  type: website
  output-dir: docs

website:
  title: "Computational statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home page
      - href: test.qmd
        text: Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

